import { useState, useEffect } from 'react';
import { FileText, Loader2, Calendar, User, Mail, Users, RefreshCw, AlertCircle, CheckCircle, Image as ImageIcon, Search } from 'lucide-react';
import { jsPDF } from 'jspdf';
import axios from 'axios';

const API_URL = 'http://localhost:5000';

export default function Dashboard({ token, user, onNavigate }) {
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');

  const fetchRecords = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await axios.get(`${API_URL}/api/records`, {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      if (response.data.success) {
        setRecords(response.data.records);
      } else {
        setError(response.data.error || 'Failed to load records');
      }
    } catch (err) {
      console.error(err);
      setError(err.response?.data?.message || 'Could not connect to the backend server.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (token) {
      fetchRecords();
    }
  }, [token]);

  const handleDownloadReport = (record) => {
    const timestamp = new Date(record.timestamp).toLocaleString();
    const modelUsed = record.model_used;
    const positiveLabel = modelUsed === 'tuberculosis' ? 'Tuberculosis' : 'Pneumonia';

    const doc = new jsPDF();
    let y = 20;

    // Title
    doc.setFontSize(18);
    doc.text('MedivioAI   Scan Report', 105, y, { align: 'center' });
    y += 12;

    // Metadata
    doc.setFontSize(11);
    doc.text(`Patient Name: ${user.name}`, 14, y); y += 6;
    doc.text(`Patient Email: ${user.email}`, 14, y); y += 6;
    if (user.age) { doc.text(`Age: ${user.age}`, 14, y); y += 6; }
    if (user.gender) { doc.text(`Gender: ${user.gender}`, 14, y); y += 6; }
    doc.text(`Generated: ${timestamp}`, 14, y); y += 6;
    doc.text(`File name: ${record.filename || 'N/A'}`, 14, y); y += 6;
    doc.text(`Disease model: ${positiveLabel}`, 14, y); y += 6;
    doc.text(`Prediction: ${record.prediction}`, 14, y); y += 6;
    doc.text(`Confidence: ${record.confidence}%`, 14, y); y += 10;

    // Notes / disclaimer
    doc.setFontSize(12);
    doc.text('Notes', 14, y);
    y += 7;
    doc.setFontSize(10);
    const notes =
      'This report is generated by an experimental AI assistant and is not a substitute for professional medical diagnosis. Always consult a qualified healthcare provider.';
    const notesLines = doc.splitTextToSize(notes, 180);
    doc.text(notesLines, 14, y);
    y += notesLines.length * 5;

    // Optional image preview from database
    if (record.image_preview) {
      y += 10;
      doc.setFontSize(12);
      doc.text('Analyzed Image', 14, y);
      y += 6;

      let imgType = 'JPEG';
      if (record.image_preview.startsWith('data:image/png')) imgType = 'PNG';

      try {
        const imgWidth = 80;
        const imgHeight = 80;
        doc.addImage(record.image_preview, imgType, 14, y, imgWidth, imgHeight);
      } catch (e) {
        console.error('PDF image error:', e);
      }
    }

    const fileDate = record.timestamp.replace(/[:.]/g, '-');
    doc.save(`medivioai_report_${fileDate}.pdf`);
  };

  const filteredRecords = records.filter(record => 
    record.prediction.toLowerCase().includes(searchTerm.toLowerCase()) ||
    record.model_used.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (record.filename && record.filename.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 animate-fade-in text-slate-100">
      {/* Welcome Banner */}
      <div className="bg-linear-to-r from-blue-750 to-slate-900 border border-blue-950 rounded-3xl p-8 md:p-12 shadow-xl shadow-slate-950/40 mb-10 relative overflow-hidden">
        <div className="absolute right-0 bottom-0 top-0 opacity-5 flex items-center justify-center pointer-events-none">
          <FileText className="h-96 w-96 translate-x-1/4 translate-y-1/4 rotate-12" />
        </div>
        <div className="relative z-10">
          <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight text-white">
            Hello, {user.name}!
          </h1>
          <p className="text-slate-350 mt-2 text-base md:text-lg max-w-2xl leading-relaxed">
            Welcome to your patient portal. Here you can view details of all your previous AI diagnostic scans and access report PDFs.
          </p>
          <div className="mt-8 flex flex-wrap gap-4">
            <button
              onClick={() => onNavigate('single')}
              className="bg-slate-100 text-slate-900 hover:bg-white px-6 py-3 rounded-xl font-bold transition-all shadow-md active:scale-98 cursor-pointer"
            >
              Start a New Scan
            </button>
          </div>
        </div>
      </div>

      <div className="grid lg:grid-cols-3 gap-8">
        {/* Left Side: Profile Details */}
        <div className="space-y-6">
          <div className="bg-slate-900 rounded-2xl border border-slate-850 p-6 shadow-md">
            <h2 className="text-base font-bold text-white mb-6 flex items-center gap-2">
              <User className="h-5 w-5 text-blue-500" />
              Patient Profile
            </h2>
            <div className="space-y-4.5">
              <div className="flex items-center gap-3.5 py-2.5 border-b border-slate-850">
                <div className="bg-blue-950/50 p-2.5 rounded-lg border border-blue-900/20 text-blue-400">
                  <User className="h-4 w-4" />
                </div>
                <div>
                  <p className="text-xs text-slate-450 font-semibold uppercase tracking-wider">Name</p>
                  <p className="text-sm font-semibold text-white mt-0.5">{user.name}</p>
                </div>
              </div>

              <div className="flex items-center gap-3.5 py-2.5 border-b border-slate-850">
                <div className="bg-blue-950/50 p-2.5 rounded-lg border border-blue-900/20 text-blue-400">
                  <Mail className="h-4 w-4" />
                </div>
                <div>
                  <p className="text-xs text-slate-450 font-semibold uppercase tracking-wider">Email</p>
                  <p className="text-sm font-semibold text-white truncate max-w-xs mt-0.5">{user.email}</p>
                </div>
              </div>

              {user.age && (
                <div className="flex items-center gap-3.5 py-2.5 border-b border-slate-850">
                  <div className="bg-blue-950/50 p-2.5 rounded-lg border border-blue-900/20 text-blue-400">
                    <Calendar className="h-4 w-4" />
                  </div>
                  <div>
                    <p className="text-xs text-slate-450 font-semibold uppercase tracking-wider">Age</p>
                    <p className="text-sm font-semibold text-white mt-0.5">{user.age} years</p>
                  </div>
                </div>
              )}

              {user.gender && (
                <div className="flex items-center gap-3.5 py-2.5 border-b border-slate-850">
                  <div className="bg-blue-950/50 p-2.5 rounded-lg border border-blue-900/20 text-blue-400">
                    <Users className="h-4 w-4" />
                  </div>
                  <div>
                    <p className="text-xs text-slate-450 font-semibold uppercase tracking-wider">Gender</p>
                    <p className="text-sm font-semibold text-white mt-0.5">{user.gender}</p>
                  </div>
                </div>
              )}
            </div>
          </div>

          <div className="bg-amber-950/25 border border-amber-900/30 rounded-2xl p-6 text-sm text-amber-300">
            <h3 className="font-bold text-amber-400 mb-2 flex items-center gap-1.5">
              <AlertCircle className="h-4 w-4" />
              Disclaimer
            </h3>
            <p className="leading-relaxed text-xs text-slate-350">
              All scans and AI reports are generated automatically. This tool is designed for educational/experimental support and should not be used as a primary diagnostic source. Always verify AI assessments with an accredited radiologist or medical professional.
            </p>
          </div>
        </div>

        {/* Right Side: Scan Records */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-slate-900 rounded-2xl border border-slate-850 p-6 shadow-md">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
              <div>
                <h2 className="text-lg font-bold text-white">Diagnosis History</h2>
                <p className="text-xs text-slate-450 mt-0.5">
                  Showing {filteredRecords.length} diagnostic records
                </p>
              </div>
              
              <div className="flex gap-2">
                <button
                  onClick={fetchRecords}
                  disabled={loading}
                  className="p-2 border border-slate-800 rounded-xl hover:bg-slate-850 text-slate-400 disabled:opacity-50 transition-colors cursor-pointer"
                  title="Refresh Records"
                >
                  <RefreshCw className={`h-5 w-5 ${loading ? 'animate-spin' : ''}`} />
                </button>
              </div>
            </div>

            {/* Search Bar */}
            <div className="relative mb-6">
              <Search className="absolute inset-y-0 left-0 pl-3.5 flex items-center text-slate-500 h-5 w-5 pointer-events-none self-center" />
              <input
                type="text"
                placeholder="Search history by result, model, filename..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="block w-full pl-10 pr-4 py-2.5 bg-slate-950 border border-slate-800 rounded-xl focus:bg-slate-900 focus:border-blue-500/50 transition-all text-sm outline-hidden text-white placeholder-slate-500"
              />
            </div>

            {/* Loading / Error States */}
            {loading && (
              <div className="text-center py-16">
                <Loader2 className="h-10 w-10 text-blue-500 animate-spin mx-auto mb-3" />
                <p className="text-slate-400 font-semibold">Loading history...</p>
              </div>
            )}

            {!loading && error && (
              <div className="bg-red-950/20 border border-red-900/30 rounded-xl p-6 text-center">
                <AlertCircle className="h-10 w-10 text-red-500 mx-auto mb-3" />
                <p className="text-sm text-red-350 font-bold mb-2">Failed to load records</p>
                <p className="text-xs text-red-400 mb-4">{error}</p>
                <button
                  onClick={fetchRecords}
                  className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg text-sm font-semibold transition-all cursor-pointer"
                >
                  Retry
                </button>
              </div>
            )}

            {/* History Table */}
            {!loading && !error && filteredRecords.length === 0 && (
              <div className="text-center py-16 border-2 border-dashed border-slate-850 rounded-xl">
                <FileText className="h-12 w-12 text-slate-500 mx-auto mb-3" />
                <p className="text-slate-400 font-semibold">No diagnostic records found</p>
                {searchTerm ? (
                  <p className="text-xs text-slate-500 mt-1">Try tweaking your search term</p>
                ) : (
                  <button
                    onClick={() => onNavigate('single')}
                    className="text-sm text-blue-450 font-semibold hover:underline mt-2 inline-block cursor-pointer"
                  >
                    Run your first scan now
                  </button>
                )}
              </div>
            )}

            {!loading && !error && filteredRecords.length > 0 && (
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-slate-850">
                  <thead>
                    <tr>
                      <th className="px-4 py-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">Scan</th>
                      <th className="px-4 py-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">Date & Model</th>
                      <th className="px-4 py-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">Result</th>
                      <th className="px-4 py-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">Confidence</th>
                      <th className="px-4 py-3 text-right text-xs font-semibold text-slate-400 uppercase tracking-wider">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-850/50 bg-slate-900">
                    {filteredRecords.map((record) => {
                      const isNormal = record.prediction === 'NORMAL';
                      const formattedDate = new Date(record.timestamp).toLocaleDateString(undefined, {
                        month: 'short',
                        day: 'numeric',
                        year: 'numeric'
                      });
                      const formattedTime = new Date(record.timestamp).toLocaleTimeString(undefined, {
                        hour: '2-digit',
                        minute: '2-digit'
                      });

                      return (
                        <tr key={record.id} className="hover:bg-slate-950/40 transition-colors">
                          <td className="px-4 py-3.5 whitespace-nowrap">
                            {record.image_preview ? (
                              <img
                                src={record.image_preview}
                                alt="Scan"
                                className="w-12 h-12 rounded-lg object-cover shadow-xs border border-slate-800"
                              />
                            ) : (
                              <div className="w-12 h-12 rounded-lg bg-slate-950 flex items-center justify-center text-slate-600 border border-slate-850">
                                <ImageIcon className="h-5 w-5" />
                              </div>
                            )}
                          </td>
                          <td className="px-4 py-3.5 whitespace-nowrap">
                            <div className="text-sm font-semibold text-white">
                              {record.model_used === 'tuberculosis' ? 'Tuberculosis Scan' : 'Pneumonia Scan'}
                            </div>
                            <div className="text-xs text-slate-450 mt-0.5">
                              {formattedDate} at {formattedTime}
                            </div>
                          </td>
                          <td className="px-4 py-3.5 whitespace-nowrap">
                            <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-bold ${
                              isNormal
                                ? 'bg-emerald-950/40 text-emerald-450 border border-emerald-900/30'
                                : 'bg-red-950/40 text-red-450 border border-red-900/30'
                            }`}>
                              {isNormal ? (
                                <CheckCircle className="h-3.5 w-3.5 shrink-0" />
                              ) : (
                                <AlertCircle className="h-3.5 w-3.5 shrink-0" />
                              )}
                              {record.prediction}
                            </span>
                          </td>
                          <td className="px-4 py-3.5 whitespace-nowrap">
                            <div className="text-sm font-bold text-white">
                              {record.confidence}%
                            </div>
                            <div className="w-20 bg-slate-950 border border-slate-900 rounded-full h-1.5 overflow-hidden mt-1">
                              <div
                                className={`h-full rounded-full ${isNormal ? 'bg-emerald-500' : 'bg-red-500'}`}
                                style={{ width: `${record.confidence}%` }}
                              ></div>
                            </div>
                          </td>
                          <td className="px-4 py-3.5 whitespace-nowrap text-right text-sm font-medium">
                            <button
                              onClick={() => handleDownloadReport(record)}
                              className="inline-flex items-center gap-1 px-3 py-1.5 border border-slate-850 rounded-lg text-xs font-bold text-slate-200 hover:bg-slate-800 transition-colors shadow-xs cursor-pointer"
                            >
                              <FileText className="h-3.5 w-3.5 text-slate-450" />
                              PDF
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
