import { useState, useRef } from 'react';
import { Upload, X, CheckCircle, AlertCircle, Loader2, Image as ImageIcon, FileText, ArrowLeft } from 'lucide-react';
import { jsPDF } from 'jspdf';
import axios from 'axios';

const API_URL = 'http://localhost:5000';

export default function SinglePrediction({ mode = 'pneumonia', onBack }) {
  const [selectedFile, setSelectedFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [model] = useState(mode === 'tuberculosis' ? 'tuberculosis' : 'pneumonia');
  const fileInputRef = useRef(null);

  const handleFileSelect = (event) => {
    const file = event.target.files?.[0];
    if (file) {
      if (!file.type.startsWith('image/')) {
        setError('Please select a valid image file');
        return;
      }
      
      setSelectedFile(file);
      setError(null);
      setResult(null);

      // Create preview
      const reader = new FileReader();
      reader.onloadend = () => {
        setPreview(reader.result);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleDrop = (event) => {
    event.preventDefault();
    const file = event.dataTransfer.files?.[0];
    if (file) {
      if (!file.type.startsWith('image/')) {
        setError('Please select a valid image file');
        return;
      }
      
      setSelectedFile(file);
      setError(null);
      setResult(null);

      const reader = new FileReader();
      reader.onloadend = () => {
        setPreview(reader.result);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleDragOver = (event) => {
    event.preventDefault();
  };

  const handleAnalyze = async () => {
    if (!selectedFile) {
      setError('Please select an image first');
      return;
    }

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const formData = new FormData();
      formData.append('image', selectedFile);
      formData.append('model', model);

      const response = await axios.post(`${API_URL}/api/predict`, formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      });

      if (response.data.success) {
        setResult(response.data);
      } else {
        setError(response.data.error || 'Analysis failed');
      }
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to connect to server. Make sure the backend is running on port 5000.');
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setSelectedFile(null);
    setPreview(null);
    setResult(null);
    setError(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleDownloadReport = () => {
    if (!result) return;

    const now = new Date();
    const timestamp = now.toLocaleString();
    const modelUsed = result.model_used || model;
    const positiveKey = modelUsed === 'tuberculosis' ? 'tuberculosis' : 'pneumonia';
    const positiveLabel = positiveKey.charAt(0).toUpperCase() + positiveKey.slice(1);

    const doc = new jsPDF();
    let y = 20;

    // Title
    doc.setFontSize(18);
    doc.text('MedivioAI  Scan Report', 105, y, { align: 'center' });
    y += 12;

    // Metadata
    doc.setFontSize(11);
    doc.text(`Generated: ${timestamp}`, 14, y); y += 6;
    doc.text(`File name: ${selectedFile?.name || 'N/A'}`, 14, y); y += 6;
    doc.text(`Disease model: ${positiveLabel}`, 14, y); y += 6;
    doc.text(`Prediction: ${result.prediction}`, 14, y); y += 6;
    doc.text(`Confidence: ${result.confidence}%`, 14, y); y += 10;

    // Probabilities
    doc.setFontSize(12);
    doc.text('Probabilities', 14, y);
    y += 7;
    doc.setFontSize(11);
    doc.text(`Normal: ${result.probability?.normal ?? 'N/A'}%`, 20, y);
    y += 6;
    doc.text(
      `${positiveLabel}: ${result.probability?.[positiveKey] ?? 'N/A'}%`,
      20,
      y
    );
    y += 10;

    // Notes / disclaimer
    doc.setFontSize(12);
    doc.text('Notes', 14, y);
    y += 7;
    doc.setFontSize(10);
    const notes =
      'This report is generated by an experimental AI assistant and is not a substitute for professional medical diagnosis. Always consult a qualified healthcare provider.';
    const notesLines = doc.splitTextToSize(notes, 180);
    doc.text(notesLines, 14, y);
    y += notesLines.length * 5;

    // Optional image preview
    if (preview) {
      y += 10;
      doc.setFontSize(12);
      doc.text('Image preview', 14, y);
      y += 6;

      let imgType = 'JPEG';
      if (preview.startsWith('data:image/png')) imgType = 'PNG';

      try {
        const imgWidth = 80;
        const imgHeight = 80;
        doc.addImage(preview, imgType, 14, y, imgWidth, imgHeight);
      } catch (e) {
        // Ignore image errors; still allow PDF download
      }
    }

    const datePart = now.toISOString().replace(/[:]/g, '-').split('.')[0];
    doc.save(`medivioai_scan_report_${datePart}.pdf`);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 animate-fade-in">
      {/* Back Button */}
      {onBack && (
        <div className="mb-6">
          <button
            type="button"
            onClick={onBack}
            className="inline-flex items-center gap-2 text-sm font-medium text-gray-700 hover:text-gray-900"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back to scan selection</span>
          </button>
        </div>
      )}

      {/* Header */}
      <div className="text-center mb-12">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          {mode === 'tuberculosis' ? 'Tuberculosis Scan' : 'Pneumonia Scan'}
        </h1>
        <p className="text-lg text-gray-600 max-w-2xl mx-auto">
          Upload a medical image and let the assistant analyze it using the
          selected disease model.
        </p>
      </div>

      <div className="grid lg:grid-cols-2 gap-8">
        {/* Upload Section */}
        <div className="space-y-6">
          <div className="bg-white rounded-2xl shadow-lg p-8 border border-gray-200">
            <h2 className="text-xl font-semibold text-gray-900 mb-6 flex items-center gap-2">
              <Upload className="h-5 w-5 text-blue-600" />
              Upload Medical Image
            </h2>

            {/* Model Indicator */}
            <div className="mb-6">
              <p className="text-sm font-medium text-gray-700 mb-1">Disease model</p>
              <p className="inline-flex items-center px-4 py-1 rounded-full text-xs font-semibold bg-blue-50 text-blue-700 border border-blue-100">
                {mode === 'tuberculosis' ? 'Tuberculosis (X-ray)' : 'Pneumonia (X-ray)'}
              </p>
            </div>

            {/* Drag and Drop Area */}
            <div
              onDrop={handleDrop}
              onDragOver={handleDragOver}
              onClick={() => fileInputRef.current?.click()}
              className="border-2 border-dashed border-gray-300 rounded-xl p-8 text-center cursor-pointer hover:border-blue-500 hover:bg-blue-50/50 transition-all"
            >
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                onChange={handleFileSelect}
                className="hidden"
              />

              {!preview ? (
                <div className="space-y-4">
                  <div className="flex justify-center">
                    <div className="bg-blue-100 p-4 rounded-full">
                      <ImageIcon className="h-10 w-10 text-blue-600" />
                    </div>
                  </div>
                  <div>
                    <p className="text-lg font-medium text-gray-900 mb-2">
                      Click to upload or drag and drop
                    </p>
                    <p className="text-sm text-gray-500">
                      PNG, JPG or JPEG (MAX. 10MB)
                    </p>
                  </div>
                </div>
              ) : (
                <div className="space-y-4">
                  <div className="relative inline-block">
                    <img
                      src={preview}
                      alt="Preview"
                      className="max-h-64 rounded-lg shadow-md"
                    />
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleReset();
                      }}
                      className="absolute -top-2 -right-2 bg-red-500 text-white p-1 rounded-full hover:bg-red-600 transition-colors"
                    >
                      <X className="h-4 w-4" />
                    </button>
                  </div>
                  <p className="text-sm text-gray-600 font-medium">
                    {selectedFile?.name}
                  </p>
                </div>
              )}
            </div>

            {/* Action Buttons */}
            <div className="flex gap-4 mt-6">
              <button
                onClick={handleAnalyze}
                disabled={!selectedFile || loading}
                className="flex-1 bg-blue-600 text-white px-6 py-3 rounded-xl font-semibold hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-all shadow-md hover:shadow-lg flex items-center justify-center gap-2"
              >
                {loading ? (
                  <>
                    <Loader2 className="h-5 w-5 animate-spin" />
                    Analyzing...
                  </>
                ) : (
                  <>
                    <FileText className="h-5 w-5" />
                    Analyze Image
                  </>
                )}
              </button>

              {selectedFile && (
                <button
                  onClick={handleReset}
                  disabled={loading}
                  className="px-6 py-3 rounded-xl font-semibold border-2 border-gray-300 text-gray-700 hover:bg-gray-50 transition-all disabled:opacity-50"
                >
                  Reset
                </button>
              )}
            </div>

            {/* Error Message */}
            {error && (
              <div className="mt-6 bg-red-50 border border-red-200 rounded-xl p-4 flex items-start gap-3">
                <AlertCircle className="h-5 w-5 text-red-600 shrink-0 mt-0.5" />
                <div>
                  <p className="text-sm font-medium text-red-900">Error</p>
                  <p className="text-sm text-red-700 mt-1">{error}</p>
                </div>
              </div>
            )}
          </div>

          {/* Info Card */}
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-6">
            <h3 className="font-semibold text-blue-900 mb-3">How to use this prototype</h3>
            <ul className="space-y-2 text-sm text-blue-800">
              <li className="flex items-start gap-2">
                <span className="text-blue-600 mt-1">•</span>
                <span>Use clear, well‑centered medical images captured from trusted sources.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-600 mt-1">•</span>
                <span>Supported formats: JPEG, JPG, PNG (maximum 10MB per image).</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-600 mt-1">•</span>
                <span>
                  This is an experimental AI assistant, not a medical device
                  and not a replacement for professional diagnosis.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-600 mt-1">•</span>
                <span>
                  Current model is tuned for pneumonia on radiology images and
                  may not generalize to all image types.
                </span>
              </li>
            </ul>
          </div>
        </div>

        {/* Results Section */}
        <div>
          <div className="bg-white rounded-2xl shadow-lg p-8 border border-gray-200 sticky top-24">
            <h2 className="text-xl font-semibold text-gray-900 mb-6">
              Analysis Results
            </h2>

            {!result && !loading && (
              <div className="text-center py-12">
                <div className="bg-gray-100 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4">
                  <FileText className="h-10 w-10 text-gray-400" />
                </div>
                <p className="text-gray-500">
                  Upload and analyze an image to see results
                </p>
              </div>
            )}

            {loading && (
              <div className="text-center py-12">
                <Loader2 className="h-12 w-12 text-blue-600 animate-spin mx-auto mb-4" />
                <p className="text-gray-600 font-medium">Analyzing image...</p>
                <p className="text-sm text-gray-500 mt-2">This may take a few seconds</p>
              </div>
            )}

            {result && (
              <div className="space-y-6 animate-fade-in">
                {/* Prediction Result */}
                <div className={`rounded-xl p-6 ${
                  result.prediction === 'PNEUMONIA' 
                    ? 'bg-red-50 border-2 border-red-200' 
                    : 'bg-emerald-50 border-2 border-emerald-200'
                }`}>
                  <div className="flex items-center gap-3 mb-3">
                    {result.prediction === 'PNEUMONIA' ? (
                      <AlertCircle className="h-8 w-8 text-red-600" />
                    ) : (
                      <CheckCircle className="h-8 w-8 text-emerald-600" />
                    )}
                    <div>
                      <p className="text-sm text-gray-600 font-medium">Prediction</p>
                      <p className={`text-2xl font-bold ${
                        result.prediction === 'PNEUMONIA' ? 'text-red-900' : 'text-emerald-900'
                      }`}>
                        {result.prediction}
                      </p>
                    </div>
                  </div>
                  <div className="mt-4">
                    <div className="flex justify-between text-sm mb-2">
                      <span className="font-medium text-gray-700">Confidence</span>
                      <span className="font-bold text-gray-900">{result.confidence}%</span>
                    </div>
                    <div className="bg-white/50 rounded-full h-3 overflow-hidden">
                      <div
                        className={`h-full rounded-full transition-all duration-1000 ${
                          result.prediction === 'PNEUMONIA' ? 'bg-red-500' : 'bg-emerald-500'
                        }`}
                        style={{ width: `${result.confidence}%` }}
                      ></div>
                    </div>
                  </div>
                </div>

                {/* Probability Breakdown */}
                <div className="space-y-4">
                  <h3 className="font-semibold text-gray-900">Detailed Probability</h3>
                  
                  <div className="space-y-3">
                    <div>
                      <div className="flex justify-between items-center mb-2">
                        <span className="text-sm font-medium text-gray-700">Normal</span>
                        <span className="text-sm font-bold text-gray-900">
                          {result.probability.normal}%
                        </span>
                      </div>
                      <div className="bg-gray-200 rounded-full h-2 overflow-hidden">
                        <div
                          className="bg-emerald-500 h-full rounded-full transition-all duration-1000"
                          style={{ width: `${result.probability.normal}%` }}
                        ></div>
                      </div>
                    </div>

                    <div>
                      <div className="flex justify-between items-center mb-2">
                        <span className="text-sm font-medium text-gray-700">
                          {result.model_used === 'tuberculosis' ? 'Tuberculosis' : 'Pneumonia'}
                        </span>
                        <span className="text-sm font-bold text-gray-900">
                          {result.model_used === 'tuberculosis'
                            ? result.probability.tuberculosis
                            : result.probability.pneumonia}%
                        </span>
                      </div>
                      <div className="bg-gray-200 rounded-full h-2 overflow-hidden">
                        <div
                          className="bg-red-500 h-full rounded-full transition-all duration-1000"
                          style={{
                            width: `${
                              result.model_used === 'tuberculosis'
                                ? result.probability.tuberculosis
                                : result.probability.pneumonia
                            }%`,
                          }}
                        ></div>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Report Download */}
                <div className="pt-2">
                  <button
                    type="button"
                    onClick={handleDownloadReport}
                    className="inline-flex items-center px-4 py-2 rounded-lg text-sm font-semibold bg-gray-900 text-white hover:bg-gray-800 transition-colors shadow-sm"
                  >
                    <FileText className="h-4 w-4 mr-2" />
                    Download report
                  </button>
                </div>

                {/* Disclaimer */}
                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                  <p className="text-xs text-yellow-800 leading-relaxed">
                    <strong>Disclaimer:</strong> This AI analysis is for informational purposes only 
                    and should not replace professional medical diagnosis. Please consult with a 
                    qualified healthcare provider for medical advice.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
