import { useState, useRef } from 'react';
import { Upload, X, CheckCircle, AlertCircle, Loader2, Image as ImageIcon, FileText, ArrowLeft } from 'lucide-react';
import { jsPDF } from 'jspdf';
import axios from 'axios';
import toast from 'react-hot-toast';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';

export default function SinglePrediction({ mode = 'pneumonia', token, onBack }) {
  const [selectedFile, setSelectedFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [model] = useState(mode === 'tuberculosis' ? 'tuberculosis' : 'pneumonia');
  const fileInputRef = useRef(null);

  const handleFileSelect = (event) => {
    const file = event.target.files?.[0];
    if (file) {
      if (!file.type.startsWith('image/')) {
        toast.error('Please select a valid image file');
        return;
      }
      
      setSelectedFile(file);
      setResult(null);

      // Create preview
      const reader = new FileReader();
      reader.onloadend = () => {
        setPreview(reader.result);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleDrop = (event) => {
    event.preventDefault();
    const file = event.dataTransfer.files?.[0];
    if (file) {
      if (!file.type.startsWith('image/')) {
        toast.error('Please select a valid image file');
        return;
      }
      
      setSelectedFile(file);
      setResult(null);

      const reader = new FileReader();
      reader.onloadend = () => {
        setPreview(reader.result);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleDragOver = (event) => {
    event.preventDefault();
  };

  const handleAnalyze = async () => {
    if (!selectedFile) {
      toast.error('Please select an image first');
      return;
    }

    setLoading(true);
    setResult(null);

    try {
      const formData = new FormData();
      formData.append('image', selectedFile);
      formData.append('model', model);

      const headers = {
        'Content-Type': 'multipart/form-data',
      };
      if (token) {
        headers['Authorization'] = `Bearer ${token}`;
      }

      const response = await axios.post(`${API_URL}/api/predict`, formData, { headers });

      if (response.data.success) {
        setResult(response.data);
        toast.success('Analysis completed');
      } else {
        toast.error(response.data.error || 'Analysis failed');
      }
    } catch (err) {
      toast.error(err.response?.data?.error || 'Failed to connect to server. Make sure the backend is running on port 5000.');
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setSelectedFile(null);
    setPreview(null);
    setResult(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleDownloadReport = () => {
    if (!result) return;

    const now = new Date();
    const timestamp = now.toLocaleString();
    const modelUsed = result.model_used || model;
    const positiveLabel = modelUsed === 'tuberculosis' ? 'Tuberculosis' : 'Pneumonia';

    const doc = new jsPDF();
    let y = 20;

    // Title
    doc.setFontSize(18);
    doc.text('MedivioAI   Scan Report', 105, y, { align: 'center' });
    y += 12;

    // Metadata
    doc.setFontSize(11);
    doc.text(`Generated: ${timestamp}`, 14, y); y += 6;
    doc.text(`File name: ${selectedFile?.name || 'N/A'}`, 14, y); y += 6;
    doc.text(`Disease model: ${positiveLabel}`, 14, y); y += 6;
    doc.text(`Prediction: ${result.prediction}`, 14, y); y += 6;
    doc.text(`Confidence: ${result.confidence}%`, 14, y); y += 10;

    // Notes / disclaimer
    doc.setFontSize(12);
    doc.text('Notes', 14, y);
    y += 7;
    doc.setFontSize(10);
    const notes =
      'This report is generated by an experimental AI assistant and is not a substitute for professional medical diagnosis. Always consult a qualified healthcare provider.';
    const notesLines = doc.splitTextToSize(notes, 180);
    doc.text(notesLines, 14, y);
    y += notesLines.length * 5;

    // Optional image preview
    if (preview) {
      y += 10;
      doc.setFontSize(12);
      doc.text('Image preview', 14, y);
      y += 6;

      let imgType = 'JPEG';
      if (preview.startsWith('data:image/png')) imgType = 'PNG';

      try {
        const imgWidth = 80;
        const imgHeight = 80;
        doc.addImage(preview, imgType, 14, y, imgWidth, imgHeight);
      } catch (e) {
        // Ignore image errors during PDF export.
      }
    }

    const datePart = now.toISOString().replace(/[:]/g, '-').split('.')[0];
    doc.save(`medivioai_scan_report_${datePart}.pdf`);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 animate-fade-in text-slate-100">
      {/* Back Button */}
      {onBack && (
        <div className="mb-6">
          <button
            type="button"
            onClick={onBack}
            className="inline-flex items-center gap-2 text-sm font-semibold text-slate-400 hover:text-white transition-colors cursor-pointer"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back to scan selection</span>
          </button>
        </div>
      )}

      {/* Header */}
      <div className="text-center mb-12">
        <h1 className="text-4xl font-extrabold text-white mb-4">
          {mode === 'tuberculosis' ? 'Tuberculosis Scan' : 'Pneumonia Scan'}
        </h1>
        <p className="text-base text-slate-400 max-w-2xl mx-auto">
          Upload a medical image and let the assistant analyze it using the
          selected disease model.
        </p>
      </div>

      <div className="grid lg:grid-cols-2 gap-8">
        {/* Upload Section */}
        <div className="space-y-6">
          <div className="bg-slate-900 rounded-3xl border border-slate-850 p-8 shadow-xl shadow-slate-950/20">
            <h2 className="text-lg font-bold text-white mb-6 flex items-center gap-2">
              <Upload className="h-5 w-5 text-blue-500" />
              Upload Medical Image
            </h2>

            {/* Model Indicator */}
            <div className="mb-6">
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Disease model</p>
              <p className="inline-flex items-center px-4 py-1.5 rounded-full text-xs font-bold bg-blue-950/50 text-blue-400 border border-blue-900/30">
                {mode === 'tuberculosis' ? 'Tuberculosis (X-ray)' : 'Pneumonia (X-ray)'}
              </p>
            </div>

            {/* Drag and Drop Area */}
            <div
              onDrop={handleDrop}
              onDragOver={handleDragOver}
              onClick={() => fileInputRef.current?.click()}
              className="border-2 border-dashed border-slate-800 hover:border-blue-500 bg-slate-950/40 rounded-2xl p-8 text-center cursor-pointer hover:bg-slate-950/80 transition-all"
            >
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                onChange={handleFileSelect}
                className="hidden"
              />

              {!preview ? (
                <div className="space-y-4">
                  <div className="flex justify-center">
                    <div className="bg-blue-950/50 p-4 rounded-full border border-blue-900/20 text-blue-400">
                      <ImageIcon className="h-10 w-10" />
                    </div>
                  </div>
                  <div>
                    <p className="text-base font-bold text-white mb-1">
                      Click to upload or drag and drop
                    </p>
                    <p className="text-xs text-slate-450">
                      PNG, JPG or JPEG (MAX. 10MB)
                    </p>
                  </div>
                </div>
              ) : (
                <div className="space-y-4">
                  <div className="relative inline-block">
                    <img
                      src={preview}
                      alt="Preview"
                      className="max-h-64 rounded-xl shadow-lg border border-slate-800"
                    />
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleReset();
                      }}
                      className="absolute -top-2 -right-2 bg-red-600 text-white p-1.5 rounded-full hover:bg-red-750 transition-colors cursor-pointer"
                    >
                      <X className="h-4 w-4" />
                    </button>
                  </div>
                  <p className="text-xs text-slate-300 font-semibold truncate max-w-xs mx-auto">
                    {selectedFile?.name}
                  </p>
                </div>
              )}
            </div>

            {/* Action Buttons */}
            <div className="flex gap-4 mt-6">
              <button
                onClick={handleAnalyze}
                disabled={!selectedFile || loading}
                className="flex-1 bg-blue-600 text-white px-6 py-3 rounded-xl font-semibold hover:bg-blue-700 disabled:bg-slate-850 disabled:text-slate-500 disabled:cursor-not-allowed transition-all shadow-md hover:shadow-lg flex items-center justify-center gap-2 cursor-pointer"
              >
                {loading ? (
                  <>
                    <Loader2 className="h-5 w-5 animate-spin" />
                    Analyzing...
                  </>
                ) : (
                  <>
                    <FileText className="h-5 w-5" />
                    Analyze Image
                  </>
                )}
              </button>

              {selectedFile && (
                <button
                  onClick={handleReset}
                  disabled={loading}
                  className="px-6 py-3 rounded-xl font-semibold border border-slate-800 text-slate-350 hover:bg-slate-850 hover:text-white transition-all disabled:opacity-50 cursor-pointer"
                >
                  Reset
                </button>
              )}
            </div>

          </div>

          {/* Info Card */}
          <div className="bg-blue-950/20 border border-blue-900/30 rounded-2xl p-6">
            <h3 className="font-bold text-blue-450 mb-3 text-sm">How to use this prototype</h3>
            <ul className="space-y-2.5 text-xs text-slate-300">
              <li className="flex items-start gap-2">
                <span className="text-blue-500 font-bold">•</span>
                <span>Use clear, well‑centered medical images captured from trusted sources.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-500 font-bold">•</span>
                <span>Supported formats: JPEG, JPG, PNG (maximum 10MB per image).</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-500 font-bold">•</span>
                <span>
                  This is an experimental AI assistant, not a medical device
                  and not a replacement for professional diagnosis.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-500 font-bold">•</span>
                <span>
                  Current model is tuned for chest radiology images and may not generalize to other styles.
                </span>
              </li>
            </ul>
          </div>
        </div>

        {/* Results Section */}
        <div>
          <div className="bg-slate-900 rounded-3xl border border-slate-850 p-8 shadow-xl shadow-slate-950/20 sticky top-24">
            <h2 className="text-lg font-bold text-white mb-6">
              Analysis Results
            </h2>

            {!result && !loading && (
              <div className="text-center py-16 border-2 border-dashed border-slate-850 rounded-2xl bg-slate-950/20">
                <div className="bg-slate-950/50 border border-slate-850 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4 text-slate-500">
                  <FileText className="h-10 w-10" />
                </div>
                <p className="text-sm text-slate-400 font-semibold">
                  Upload and analyze an image to see results
                </p>
              </div>
            )}

            {loading && (
              <div className="text-center py-16">
                <Loader2 className="h-12 w-12 text-blue-500 animate-spin mx-auto mb-4" />
                <p className="text-white font-bold">Analyzing image...</p>
                <p className="text-xs text-slate-450 mt-1">This may take a few seconds</p>
              </div>
            )}

            {result && (
              <div className="space-y-6 animate-fade-in">
                {/* Prediction Result */}
                <div className={`rounded-2xl p-6 border ${
                  result.prediction !== 'NORMAL' 
                    ? 'bg-red-950/40 border-red-900/30 text-red-400' 
                    : 'bg-emerald-950/40 border-emerald-900/30 text-emerald-400'
                }`}>
                  <div className="flex items-center gap-4.5 mb-4">
                    {result.prediction !== 'NORMAL' ? (
                      <AlertCircle className="h-9 w-9 text-red-500" />
                    ) : (
                      <CheckCircle className="h-9 w-9 text-emerald-500" />
                    )}
                    <div>
                      <p className="text-xs text-slate-400 font-semibold uppercase tracking-wider">Prediction</p>
                      <p className="text-2xl font-bold mt-0.5">
                        {result.prediction}
                      </p>
                    </div>
                  </div>
                  
                  <div className="mt-4 pt-2 border-t border-slate-850">
                    <div className="flex justify-between text-xs font-semibold mb-2">
                      <span className="text-slate-450">Confidence</span>
                      <span className="text-white font-bold">{result.confidence}%</span>
                    </div>
                    <div className="bg-slate-950 border border-slate-900 rounded-full h-3 overflow-hidden">
                      <div
                        className={`h-full rounded-full transition-all duration-1000 ${
                          result.prediction !== 'NORMAL' ? 'bg-red-500' : 'bg-emerald-500'
                        }`}
                        style={{ width: `${result.confidence}%` }}
                      ></div>
                    </div>
                  </div>
                </div>

                {/* Report Download */}
                <div className="pt-2">
                  <button
                    type="button"
                    onClick={handleDownloadReport}
                    className="inline-flex items-center px-4.5 py-2.5 rounded-xl text-sm font-bold bg-slate-100 text-slate-900 hover:bg-slate-200 transition-colors shadow-sm cursor-pointer"
                  >
                    <FileText className="h-4 w-4 mr-2" />
                    Download report
                  </button>
                </div>

                {/* Disclaimer */}
                <div className="bg-yellow-950/20 border border-yellow-900/20 rounded-xl p-4">
                  <p className="text-xs text-yellow-300 leading-relaxed">
                    <strong>Disclaimer:</strong> This AI analysis is for informational purposes only 
                    and should not replace professional medical diagnosis. Please consult with a 
                    qualified healthcare provider for medical advice.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
